### ISSUE TITLE
Uue sünohulga tekitamisel ei salvestu lisatud sõna, ei värskendata sünohulga infot

### ISSUE THREAD

**Issue by nostneji** [BitWeb/wordnet-workbench-client#1]
Kontekst: Client: v0.2.6. API: v0.4.6. Server: http://dev.keeleressursid.ee

Vaatleme uue sünohulga defineerimise stsenaariumi:
1) valime menüüst '+ New' / 'Empty Synset';
2) süsteem kuvab uue sünohulga vormi 'New synset';
3) valime vaate 'Sense variants' ja vajutame nupule 'Create new sense';
4) süsteem kuvab uue sõna lisamise vormi 'New sense';
5) olles vaatel 'Attributes' sisestame soovitud sõna väljale 'Lemma' ja vajutame vormil 'New sense' nupule 'Save';
6) süsteem sulgeb sõna lisamise vormi ja uuendab sünohulga vormil vaates 'Sense variants' olevat sõnade nimistut ja näitab seal lisatud sõna;
7) vajutame vormil 'New synset' nupule 'Save';
8) süsteem sulgeb uue sünohulga lisamise vormi ja avab olemasoleva sünohulga vormi, kus on 3 andmeplokki: 'Anchor', seoste vaated ja 'Synset'.

Õige käitumise korral peavad sammul (8) kuvatud andmeplokid olema väärtustatud äsja sisestatud sünohulga andmetega.

Praeguses versioonis aga väärtustatakse need andmeblokid sellise sünohulga andmete järgi, mis sisaldab küll äsja loodud sünohulga ID ja Label väärtust, kuid kõik muu on puudu:
- 'Anchor' väljal puudub info sisestatud sõna kohta;
- seoste vaates puudub info sisestatud sõna kohta;
- vormi 'Synset' päises puudub info sisestatud sõna kohta;
- vormi 'Synset' vaates 'Sense variants' puudub rida sisestatud sõna kohta.

Testides on tulnud ette nii seda, et sõna ja sünohulga vahele seatakse seos, kui ka seda, et seost ei tekitata. Vastav situatsioon on API poole pöördumise logis järgmine:

POST /api/v1/sense/  -- tekitab uue sõna;
POST /api/v1/synset/  -- tekitab uue sünohulga;
GET /api/v1/sense/657/  -- küsib sõna objekti tagasi;
GET /api/v1/synset/453/  -- küsib sünohulga objekti tagasi;
PUT /api/v1/sense/657/  -- lisab sõnale seose sünohulgaga; osadel juhtudel seda viimast operatsiooni ei tehta.

Kui sõna ja sünohulga seos siiski salvestus, siis pärast mõne teise sünohulga andmete vaatamist ja seejärel vaadeldava sünohulga juurde tagasi tulles on kuvatav info korrektne.

**Comment by Ivarpoiss** [comment]
Andmete värskendamise probleemi tekitab viimati lisatud muudatuste tuvastamise feature (Takistab vaate uuesti laadimist). Sama viga tekkis mul ka sense vormil. Probleeme tekitas ka url-i copy-paste brauseri aadressireal. Järgmises commitis tuleb parandus.
