### ISSUE TITLE
Sõna definitsioon salvestatakse kahekordselt

### ISSUE THREAD

**Issue by nostneji** [BitWeb/wordnet-workbench-client#2]
Kontekst: Client: v0.2.6. API: v0.4.6. Server: http://dev.keeleressursid.ee

Võtame stsenaariumi lähtepunktiks olukorra, kus meil on avatud olemasoleva sünohulga vaade 'Sense variants' ja selle alla on avatud (nupuga 'View/edit') olemasoleva sõna vorm 'Sense ...' ning sellel on aktiivne vaade 'Definitions'.

1) vajutame nupule 'Add new';
2) süsteem avab vormi 'Sense definition' (aga ei vii fookust sellele vormile, mistõttu kasutaja ei pruugi seda näha), väljale 'Language' on vaikimisi võetud väärtus aktiivse leksikoni järgi;
3) liigume lehel allapoole, et leida avatud vorm 'Sense definition', sisestame soovitud teksti väljale 'Definition text' ja vajutame vormi 'Sense definition' nupule 'Save';
4) süsteem kuvab sisestatud definitsiooni vormi 'Sense ...' vaate 'Definitions' nimistus ja EI sulge vormi 'Sense definition';
5) sõna andmestikus tehtud muutuse salvestamiseks vajutame vormil 'Sense ...' nupule 'Save';
6) süsteem sulgeb vormi 'Sense definition', lisab veelkord eelnevalt sisestatud definitsiooni sõna juures olevate definitsioonide nimistusse (nüüd on seal 2 samasugust) ja salvestab andmed.

PUT /api/v1/sense/658/
`{"id":658,"lexical_entry":{"id":643,"lexicon":2,"part_of_speech":"n","lemma":"pärslane","distinctive_case":null,"distinctive_form":null,"scheme":null,"grammatical_number":"sg","grammatical_gender":"n","created_by":"test","date_created":"2016-06-16T08:41:02.487967Z","updated_by":"test","date_updated":"2016-06-16T09:30:23.705989Z"},"nr":1,"label":"pärslane_1(n)","synset":454,"style":null,"geography":null,"status":"D","comment":null,"primary_definition":"","primary_example":"","sense_definitions":[{"language":"est","statements":[],"text":"pärsia tõugu kass"},{"language":"est","statements":[],"text":"pärsia tõugu kass"}],"examples":[],"sense_externals":[],"created_by":"test","date_created":"2016-06-16T08:41:02.495967Z","updated_by":"test","date_updated":"2016-06-16T09:30:23.713163Z","locked_by":null,"date_locked":null}`

**Comment by Ivarpoiss** [comment]
Veaparandus tuleb järgmise commitiga.

**Comment by Ivarpoiss** [comment]
Peaks olema parandatud commitga e1d53ea3dcb18e9e3dafbf558980b0e198a9b1df
